my:
  greeting: Updated Hello World from config server
  list:
    values: One, Two, Three, Four
db:
  connection: connection-spring-here-from-config-server
  host: www.googlLocalhostd.com
  port: 12008999
